?

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -147,6 +147,9 @@ jobs:
       - name: Make next_env.txt world-readable
         run: |
           ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ env.HOST }} "chmod 644 /tmp/next_env.txt"
+      - name: Debug print next_env.txt
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ env.HOST }} "cat /tmp/next_env.txt || echo 'File not found'"
       - name: Download next_env.txt
         uses: appleboy/scp-action@v0.1.4
         with:
diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -146,6 +146,9 @@ jobs:
       - name: Make next_env.txt world-readable
         run: |
           ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ env.HOST }} "chmod 644 /tmp/next_env.txt"
+      - name: Debug print next_env.txt
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ env.HOST }} "cat /tmp/next_env.txt || echo 'File not found'"
       - name: Download next_env.txt
         uses: appleboy/scp-action@v0.1.4
         with:
@@ -155,6 +158,8 @@ jobs:
           source: /tmp/next_env.txt
           target: .
           strip_components: 0
+          debug: true
+          tar_tmp_path: /tmp
       - name: Set NEXT_ENV output
         id: set-next-env
         run: |
